name: DyNaMol Compilation
on: [push]
jobs:
  Compilation-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: Upgrade packages
        run: sudo apt-get install -y libatlas-base-dev libmetis-dev libopenmpi-dev libpetsc-dev libmumps-dev libslepc-dev
      - run: mkdir build
      - name: Prepare environment
        run: cmake -B build .
      - name: Make binaries
        run: |
         cd build
         make
      - run: echo "🍏 This job's status is ${{ job.status }}."
