name: Sparselizard Compilation
on: [push]
jobs:
  Compilation-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test the code on the runner."
      - name: Install mandatory packages
        run: sudo apt-get install -y libopenblas-dev libmetis-dev libopenmpi-dev libmumps-dev petsc-dev slepc-dev libgmsh-dev
      - run: mkdir build
      - name: Prepare environment
        run: cmake -B build .
      - name: Make binaries
        run: |
         cd build
         make -j 2
      - run: echo "🍏 This job's status is ${{ job.status }}."
